# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
# Minecraft 26.1+ requires Java 25 for the Gradle JVM.

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Minecraft Version
mc_ver=1.21.10

# Plugin Versions
loom_version=1.15.5
manifold_version=2026.1.3

# Mod Properties
mod_version=1.1.1
maven_group=cc.spea.booktweaks
archives_base_name=book-tweaks
